Feature/additional claims issues
MultifactorLab/multifactor-selfservice-portal pull request #41
Opened 2023-03-10 09:24 UTC by Gimemor

### Additional Claims Issues Rework
#### New
- The Claims condition format was changed
- 'In' operator support was removed
- New array comparison logic while claim condition evaluation
#### Bugfixes
- Configuration Issue with single claim binding to array  was fixed

2023-03-10 13:21 UTC, apashkov-ext requested changes

2023-03-10 13:21 UTC, apashkov-ext commented on src/MultiFactor.SelfService.Linux.Portal/Core/Authentication/AdditionalClaims/Description/Conditions/ClaimConditionEvaluator.cs
> +            if (leftValue.Count() > 1 && rightValue.Count() > 1)
Наверно, имелось в виду это:
if (leftValue.Count() == rightValue.Count())

2023-03-10 13:21 UTC, apashkov-ext commented on src/MultiFactor.SelfService.Linux.Portal/Core/Authentication/AdditionalClaims/Description/Conditions/ClaimConditionEvaluator.cs
> +            return rightValue.Count() > 1 && leftValue.Count() == 1?
пробел добавить надо

2023-03-10 13:21 UTC, apashkov-ext commented on src/MultiFactor.SelfService.Linux.Portal/Core/Authentication/AdditionalClaims/Description/Conditions/ClaimConditionEvaluator.cs
> +            return rightValue.Count() > 1 && leftValue.Count() == 1?
Это условие некорректно сработает (см. комментарий на 37 строке). Значит, не покрыл тестами случай, когда left.length == right.length

2023-03-10 13:21 UTC, apashkov-ext commented on src/MultiFactor.SelfService.Linux.Portal/Settings/AdditionalClaim.cs
> +        public List<Claim> Claims { get; set; } = new List<Claim>();
почему убрал private?

2023-03-10 13:21 UTC, apashkov-ext commented on src/MultiFactor.SelfService.Linux.Portal/Settings/AdditionalClaim.cs
> +        private Claim SingleClaim { get; set; } = new Claim();
Аналогично. И еще добавить nullable:
private Claim? SingleClaim { get; set; } = new Claim();

2023-03-10 13:21 UTC, apashkov-ext commented on src/MultiFactor.SelfService.Linux.Portal/Core/Authentication/AdditionalClaims/Description/AdditionalClaimDescriptorsProvider.cs
> +            _portalSettings.AdditionalClaims.EnsureArraysBinging();
Зачем это здесь? Это должно выполняться на этапе сбора конфига

2023-03-10 13:21 UTC, apashkov-ext commented on src/MultiFactor.SelfService.Linux.Portal/Settings/AdditionalClaim.cs
> +        public void EnsureArraysBinging()
public IList<Claim> GetClaims() 
{
  if (Claims.Any()) return Claims;
  if (SingleClaim != null) return new List<Claim> { SingleClaim };
return Array.Empty<Claim>();
}

2023-03-12 02:12 UTC, Gimemor commented on src/MultiFactor.SelfService.Linux.Portal/Core/Authentication/AdditionalClaims/Description/Conditions/ClaimConditionEvaluator.cs
> +            return rightValue.Count() > 1 && leftValue.Count() == 1?
@apashkov-ext Такой тест есть, Evaluate_EqOperationWithAttrsAndAttrs_ShouldReturnTrue

2023-03-12 02:17 UTC, Gimemor commented on src/MultiFactor.SelfService.Linux.Portal/Core/Authentication/AdditionalClaims/Description/Conditions/ClaimConditionEvaluator.cs
> +            if (leftValue.Count() > 1 && rightValue.Count() > 1)
@apashkov-ext По замыслу это ветка для сравнения массивов, там необязательно равное количество элементов, поэтому строгое равенство не подойдет.

Всего этот метод обрабатывает три случая:
1) Сравнение двух литералов
2) Сравнение двух массивов
3) Сравнение массива и литерала

2023-03-13 07:52 UTC, apashkov-ext approved these changes

2023-03-13 09:19 UTC, apashkov-ext approved these changes

2023-03-13 10:41 UTC, merged